// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByfjpm6aK_jqQiENhZoMv9-tG-OScYa5A',
    appId: '1:972061171991:web:89c975ec0e512231fb9752',
    messagingSenderId: '972061171991',
    projectId: 'messenger-c3a59',
    authDomain: 'messenger-c3a59.firebaseapp.com',
    storageBucket: 'messenger-c3a59.firebasestorage.app',
    measurementId: 'G-KTFJ4CSEFF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrajPtxpraRLevfi9Vz_f2brr09Xj1uCA',
    appId: '1:972061171991:android:e8acf4512d0dc6c6fb9752',
    messagingSenderId: '972061171991',
    projectId: 'messenger-c3a59',
    storageBucket: 'messenger-c3a59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpi_jc4bpObtL9c5wmhfB9I3soHjruCzA',
    appId: '1:972061171991:ios:c3fe45344058be4bfb9752',
    messagingSenderId: '972061171991',
    projectId: 'messenger-c3a59',
    storageBucket: 'messenger-c3a59.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpi_jc4bpObtL9c5wmhfB9I3soHjruCzA',
    appId: '1:972061171991:ios:c3fe45344058be4bfb9752',
    messagingSenderId: '972061171991',
    projectId: 'messenger-c3a59',
    storageBucket: 'messenger-c3a59.firebasestorage.app',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByfjpm6aK_jqQiENhZoMv9-tG-OScYa5A',
    appId: '1:972061171991:web:4fa5b22a9e89f560fb9752',
    messagingSenderId: '972061171991',
    projectId: 'messenger-c3a59',
    authDomain: 'messenger-c3a59.firebaseapp.com',
    storageBucket: 'messenger-c3a59.firebasestorage.app',
    measurementId: 'G-8PT1KT8QD3',
  );
}
